package main

import (
	"github.com/micmonay/keybd_event"
)

var Binds = map[string]int{
	"a":  keybd_event.VK_A,
	"1":  keybd_event.VK_1,
	"2":  keybd_event.VK_2,
	"3":  keybd_event.VK_3,
	"4":  keybd_event.VK_4,
	"5":  keybd_event.VK_5,
	"6":  keybd_event.VK_6,
	"7":  keybd_event.VK_7,
	"8":  keybd_event.VK_8,
	"9":  keybd_event.VK_9,
	"0":  keybd_event.VK_0,
	"q":  keybd_event.VK_Q,
	"w":  keybd_event.VK_W,
	"e":  keybd_event.VK_E,
	"r":  keybd_event.VK_R,
	"t":  keybd_event.VK_T,
	"y":  keybd_event.VK_Y,
	"u":  keybd_event.VK_U,
	"i":  keybd_event.VK_I,
	"o":  keybd_event.VK_O,
	"p":  keybd_event.VK_P,
	"s":  keybd_event.VK_S,
	"d":  keybd_event.VK_D,
	"f":  keybd_event.VK_F,
	"g":  keybd_event.VK_G,
	"h":  keybd_event.VK_H,
	"j":  keybd_event.VK_J,
	"k":  keybd_event.VK_K,
	"l":  keybd_event.VK_L,
	"z":  keybd_event.VK_Z,
	"x":  keybd_event.VK_X,
	"c":  keybd_event.VK_C,
	"v":  keybd_event.VK_V,
	"b":  keybd_event.VK_B,
	"n":  keybd_event.VK_N,
	"m":  keybd_event.VK_M,
	"-":  keybd_event.VK_MINUS,
	"=":  keybd_event.VK_EQUAL,
	"]":  keybd_event.VK_LEFTBRACE,
	"[":  keybd_event.VK_RIGHTBRACE,
	"\n": keybd_event.VK_ENTER,
	";":  keybd_event.VK_SEMICOLON,
	"'":  keybd_event.VK_APOSTROPHE,
	"/":  keybd_event.VK_BACKSLASH,
	",":  keybd_event.VK_COMMA,
	".":  keybd_event.VK_DOT,
	" ":  keybd_event.VK_SPACE,
}
